### ISSUE TITLE
RuntimeError: Expected object of scalar type Long but got scalar type Byte

### ISSUE THREAD

**Issue by Abanoub-G** [jmiemirza/DUA#5]
Hi, 
Thanks a lot for the very interesting paper. I am trying to run some your experiments but I keep on getting the error below. Have you encountered this error before, whilst running your experiments?  I have tried to look up why it happens and it seems to be either because a mismatch in the number of classes defined or a different tensor scalar type according to this  [thread](https://stackoverflow.com/questions/55762581/expected-object-of-scalar-type-long-but-got-scalar-type-byte-for-argument-2-ta). However, I don't think neither of these should be an issue as I have not done any changes to the repo. Any help would be greatly appreciated. Thanks in advance. Below is the command I ran and the logs I got. 

I ran the below command following the guidance on the repo:
`python3 main.py --device 0 --dataset cifar10 --model wrn --ckpt_path Hendrycks2020AugMixWRN.pt --dataroot datasets/CIFAR10
`

Error: 

[MAIN] ------------------------------------ NEW RUN ------------------------------------
[MAIN] Running: main.py --device 0 --dataset cifar10 --model wrn --ckpt_path Hendrycks2020AugMixWRN.pt --dataroot datasets/CIFAR10
[MAIN] Full args list:
[MAIN] usr: None
[MAIN] dataroot: datasets/CIFAR10
[MAIN] ckpt_path: Hendrycks2020AugMixWRN.pt
[MAIN] dataset: cifar10
[MAIN] model: wrn
[MAIN] logfolder: logs
[MAIN] tasks: []
[MAIN] scenario: ['online', 'offline']
[MAIN] robustness_severities: ['5']
[MAIN] fog_severities: ['fog_30']
[MAIN] rain_severities: ['200mm']
[MAIN] snow_severities: ['5']
[MAIN] checkpoints_path: checkpoints
[MAIN] num_runs: 1
[MAIN] methods: ['dua']
[MAIN] num_samples: 80
[MAIN] decay_factor: 0.94
[MAIN] min_mom: 0.005
[MAIN] no_disc_adaption: False
[MAIN] lr: 0.01
[MAIN] initial_task_lr: 0.01
[MAIN] epochs: 150
[MAIN] batch_size: 8
[MAIN] workers: 1
[MAIN] yolo_lr_adjustment: thirds
[MAIN] patience: 4
[MAIN] lr_factor: 0.3333333333333333
[MAIN] verbose: True
[MAIN] max_unsuccessful_reductions: 3
[MAIN] split_ratio: 0.35
[MAIN] split_seed: 42
[MAIN] depth: 26
[MAIN] width: 1
[MAIN] group_norm: 0
[MAIN] rotation_type: rand
[MAIN] weights: yolov3.pt
[MAIN] cfg: 
[MAIN] img_size: [640, 640]
[MAIN] rect: False
[MAIN] device: 0
[MAIN] adam: False
[MAIN] start_disjoint_offline_from_initial: False
[MAIN] use_freezing_heads_ckpts: False
[MAIN] conf_thres: 0.001
[MAIN] iou_thres: 0.6
[MAIN] augment: False
[MAIN] nosave: False
[MAIN] notest: False
[MAIN] noautoanchor: False
[MAIN] bucket: 
[MAIN] cache_images: False
[MAIN] image_weights: False
[MAIN] multi_scale: False
[MAIN] single_cls: False
[MAIN] sync_bn: False
[MAIN] local_rank: -1
[MAIN] log_imgs: 16
[MAIN] log_artifacts: False
[MAIN] project: runs/train
[MAIN] name: exp
[MAIN] exist_ok: False
[MAIN] quad: False
[MAIN] kitti_to_yolo_labels: None
[MAIN] logfile: logs/20230321_153023.txt
[MAIN] ---------------------------------------------------------------------------------
[DUA] Task - gaussian_noise :::: Level - 5
[MAIN] Exception occured:
Traceback (most recent call last):
  File "main.py", line 183, in <module>
    main(args)
  File "main.py", line 43, in main
    methods.dua(args, net)
  File "/home/DUA/methods/dua.py", line 66, in dua
    res = test(valid_loader, net)[0] * 100
  File "/home/DUA/utils/testing.py", line 18, in test
    loss = criterion(outputs, labels)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1047, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2693, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/functional.py", line 2388, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Byte for argument #2 'target' in call to _thnn_nll_loss_forward

**Comment by Abanoub-G** [comment]
SOLUTION: not sure what was causing the issue, however, using this docker image of pytorch (pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel) and installing the packages listed below made the experiments run for me: 

pip3 install colorama==0.3.7
pip3 install coremltools==6.1
pip3 install matplotlib
pip3 install numpy
pip3 install onnx
pip3 install pandas
pip3 install Pillow
pip3 install protobuf
pip3 install pycocotools
pip3 install PyYAML
pip3 install requests
pip3 install scipy
pip3 install seaborn
pip3 install setuptools
pip3 install thop
pip3 install tqdm
pip3 install wandb

apt-get update
apt-get install python3-dev
apt-get install libgl1-mesa-glx
apt-get install wget
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
pip3 install opencv-contrib-python
